spring:
  datasource:
    url: jdbc:h2:mem:taskflow
    driver-class-name: org.h2.Driver
    username: suraj
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
    secret: mySuperSecretJwtKeyThatIsAtLeast32CharactersLong12345
    expiration-ms: 3600000